from fpdf import FPDF
import datetime

class AlgosincReport(FPDF):
    def header(self):
        self.set_fill_color(20, 20, 20)
        self.rect(0, 0, 210, 40, 'F')
        self.set_xy(10, 15)
        self.set_font("Arial", "B", 16)
        self.set_text_color(255, 102, 0)
        self.cell(0, 10, "POLYBIO DALY SIMULATION REPORT", 0, 1, "L")
        self.set_font("Arial", "", 10)
        self.set_text_color(255, 255, 255)
        self.cell(0, 5, f"Generated by Algosinc LLC | {datetime.date.today()}", 0, 1, "L")

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, "Confidential Scientific Simulation Output", 0, 0, "C")

def generate_pdf(results, interventions):
    pdf = AlgosincReport()
    pdf.add_page()
    pdf.ln(30)
    
    pdf.set_font("Arial", "B", 12)
    pdf.set_text_color(20, 20, 20)
    pdf.cell(0, 10, "Simulation Summary", 0, 1)
    
    pdf.set_font("Arial", "", 11)
    pdf.cell(100, 10, "Baseline DALYs (Global Burden):", 0, 0)
    pdf.cell(0, 10, f"{results['baseline']:,}", 0, 1)
    pdf.cell(100, 10, "Simulated DALYs (With Interventions):", 0, 0)
    pdf.cell(0, 10, f"{results['simulated']:,}", 0, 1)
    
    pdf.set_font("Arial", "B", 11)
    pdf.set_text_color(0, 150, 0)
    pdf.cell(100, 10, "Total DALYs Averted:", 0, 0)
    pdf.cell(0, 10, f"{results['averted']:,} ({results['reduction_pct']}%)", 0, 1)
    
    pdf.ln(10)
    pdf.set_text_color(20, 20, 20)
    pdf.cell(0, 10, "Selected Interventions:", 0, 1)
    pdf.set_font("Arial", "", 10)
    for k, v in interventions.items():
        status = "ENABLED" if v else "DISABLED"
        pdf.cell(0, 7, f"- {k.replace('_', ' ').title()}: {status}", 0, 1)
        
    pdf.output("data/processed/Simulation_Report.pdf")
    return "data/processed/Simulation_Report.pdf"